//Ejercicio 4.1

POST http://localhost:3001/api/blogs
Content-Type: application/json
//Ejercicio 4.19
//Change this for play
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iktva3kiLCJpZCI6IjYwY2M2NTUxZjk0YmRkMTU1ODJkMDUxZSIsImlhdCI6MTYyNDAxNjY1NH0.1Rw4e0Z7VDoV1PLeXuHUdVtwLkbgujqNRLEOjak0TiE

{
    "title": "Koky Blog 3 Pruebba",
    "author": "Alguien raro 3",
    "url": "http://www.marca3.es",
    "likes": 0
    //Ejercicio 4.17 && 4.18
    //"userId": "60cc6551f94bdd15582d051e"
}